version: '3'


services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: new-shop
    volumes:
      - ./postgres:/var/lib/postgresql/data